In [1]:
import numpy as np

In [4]:
arr1 = np.array(10)

In [5]:
arr1

array(10)

In [6]:
arr2 = np.array([100,200,300])
arr2

array([100, 200, 300])

In [7]:
arr3 = np.array([
    [10,20,30]
])
arr3

array([[10, 20, 30]])

In [8]:
arr4 = np.array([[[1000,2000,3000]]])
arr4

array([[[1000, 2000, 3000]]])

In [11]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [21]:
arr5 = np.array(
    [
        [
            [
                [100,200],
                [650,450]
            ],
            [
                [300,400],
                [300,400]
            ],
            [
                [500,600],
                [500,600]
            ]
        ]
])
arr5
arr5.ndim

4

In [22]:
arr6 = np.array(
    [
        [
            [
                [100,200],
                [650,450],
                [300,400],
                [300,400],
                [500,600],
                [500,600]
            ]
        ]
])
arr6
arr6.ndim

4

In [23]:
arr7 = np.array(
    [
        [
            [
                [
                    10,20,30,40,50
                ]
            ]
        ]
    ]
)
print(arr7)
arr7.ndim

[[[[10 20 30 40 50]]]]


4

In [36]:
myarr = np.array([100,200,300,400,500],ndmin=2)
myarr
myarr.ndim

2

In [39]:
print(myarr)

[[100 200 300 400 500]]


In [ ]:
print(myarr[0]) 

In [40]:
myarr = [
    [10,20,30],
    [40,50,60],
    [70,80,90]
]
print(myarr)

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [41]:
print(myarr[0])

[10, 20, 30]


In [42]:
print(myarr[1])

[40, 50, 60]


In [43]:
print(myarr[2])

[70, 80, 90]


In [47]:
print(len(myarr))
print(len(myarr[0]))
print(len(myarr[1]))
print(len(myarr[2]))

3
3
3
3
